cloud:
  aws:
    credentials:
      access-key: AKIA3LCCTRGJEINWRD4K
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: edu-eval-bucket
    prefix: https://edu-eval-bucket.s3.us-east-1.amazonaws.com/

spring: 
  servlet: 
    multipart: 
      max-file-size: 10MB 
      max-request-size: 10MB


# spring:
#   servlet:
#     multipart:
#       enabled: true
#       file-size-threshold: 2MB
#       max-file-size: 5MB
#       max-request-size: 10MB

# server:
#   port: 9090
